theory:
  classy:
    path: null
    speed: 0.2
    stop_at_error: false
    extra_args:
      Omega_k: 0
      lensing: true
      output: tCl,pCl,lCl,mPk
      N_ncdm: 1
      m_ncdm: 0.056
      background_verbose: 1
      omega_b: 0.02215
      omega_cdm: 0.13448
      tau_reio: 0.05152
      n_s: 0.98546
    ignore_obsolete: false
    renames:
      As: A_s
      ns: n_s
      nrun: alpha_s
      nrunrun: beta_s
      nt: n_t
      ntrun: alpha_t
      rdrag: rs_drag
      omegak: Omega_k
      omegal: Omega_Lambda
      w: w0_fld
      wa: wa_fld
      omegabh2: omega_b
      omegab: Omega_b
      omegach2: omega_cdm
      omegac: Omega_cdm
      omegam: Omega_m
      omegan: Omega_nu
      tau: tau_reio
      zrei: z_reio
      deltazrei: reionization_width
      helium_redshift: helium_fullreio_redshift
      helium_delta_redshift: helium_fullreio_width
      yhe: YHe
      yheused: YHe
    version: v3.3.3
    input_params:
    - H0
    output_params: []
likelihood:
  planck_2018_lowl.TT:
    lmin: 2
    lmax: 29
    type: CMB
    aliases:
    - lowT
    speed: -1
    stop_at_error: false
    version: null
    input_params: []
    output_params: []
  planck_2018_lowl.EE:
    type: CMB
    aliases:
    - lowE
    speed: -1
    stop_at_error: false
    version: null
    input_params: []
    output_params: []
  bao.sixdf_2011_bao:
    path: null
    rs_rescale: 1.027369826
    data:
    - 0.106
    - 0.336
    - 0.015
    - rs_over_DV
    aliases:
    - BAO
    speed: 5000
    type: BAO
    measurements_file: null
    rs_fid: null
    prob_dist: null
    cov_file: null
    invcov_file: null
    redshift: null
    observable_1: null
    observable_2: null
    observable_3: null
    grid_file: null
    stop_at_error: false
    version: null
    input_params: []
    output_params: []
  sn.pantheon:
    path: null
    dataset_file: Pantheon/full_long.dataset
    dataset_params: null
    aliases:
    - Pantheon
    - Pantheon18
    use_abs_mag: false
    speed: 100
    type: SN
    stop_at_error: false
    version: null
    input_params: []
    output_params: []
  sn.pantheonplus:
    path: null
    dataset_file: PantheonPlus/config.dataset
    dataset_params: null
    aliases:
    - PantheonPlus
    use_abs_mag: false
    speed: 100
    type: SN
    stop_at_error: false
    version: null
    input_params: []
    output_params: []
  sn.pantheonplusshoes:
    path: null
    dataset_file: PantheonPlus/config.dataset
    dataset_params: null
    aliases:
    - PantheonPlusSHOES
    use_abs_mag: false
    speed: 100
    type: SN
    stop_at_error: false
    version: null
    input_params: []
    output_params: []
  sn.desy5:
    path: null
    dataset_file: DESY5/config.dataset
    dataset_params: null
    aliases:
    - DESY5
    use_abs_mag: false
    speed: 100
    type: SN
    stop_at_error: false
    version: null
    input_params: []
    output_params: []
  sn.jla:
    path: null
    dataset_file: JLA/jla.dataset
    dataset_params: null
    alpha_beta_names:
    - alpha_jla
    - beta_jla
    use_abs_mag: false
    aliases:
    - JLA
    speed: 20
    type: SN
    stop_at_error: false
    version: null
    input_params:
    - alpha_jla
    - beta_jla
    output_params: []
  sn.jla_lite.JLA_lite:
    path: null
    dataset_file: JLA/jla.dataset
    dataset_params: null
    marginalize: true
    precompute_covmats: true
    use_abs_mag: false
    marginalize_params:
      marge_steps: 7
      alpha_centre: 0.14
      beta_centre: 3.123
      step_width_alpha: 0.003
      step_width_beta: 0.04
    aliases:
    - JLA
    speed: 10
    type: SN
    stop_at_error: false
    version: null
    input_params: []
    output_params: []
  sn.union3:
    dataset_file: Union3/full_long.dataset
    dataset_params: null
    aliases:
    - Union3
    use_abs_mag: false
    speed: 100
    path: null
    type: SN
    stop_at_error: false
    version: null
    input_params: []
    output_params: []
params:
  H0:
    prior:
      min: 66
      max: 74
    ref:
      dist: norm
      loc: 70.52
      scale: 1.0
    proposal: 0.5
    latex: H_0
  alpha_jla:
    prior:
      min: 0.01
      max: 2
    ref:
      dist: norm
      loc: 0.14
      scale: 0.005
    proposal: 0.005
    latex: \alpha_\mathrm{JLA}
  beta_jla:
    prior:
      min: 0.9
      max: 4.6
    ref:
      dist: norm
      loc: 3.1
      scale: 0.05
    proposal: 0.05
    latex: \beta_\mathrm{JLA}
  chi2__BAO:
    latex: \chi^2_\mathrm{BAO}
    derived: true
  chi2__CMB:
    latex: \chi^2_\mathrm{CMB}
    derived: true
  chi2__SN:
    latex: \chi^2_\mathrm{SN}
    derived: true
sampler:
  mcmc:
    sampler_type: mcmc
    supports_periodic_params: true
    burn_in: 0
    max_tries: 40d
    covmat: null
    covmat_params: null
    proposal_scale: 2.4
    output_every: 60s
    learn_every: 40d
    temperature: 1
    learn_proposal: true
    learn_proposal_Rminus1_max: 2.0
    learn_proposal_Rminus1_max_early: 30.0
    learn_proposal_Rminus1_min: 0.0
    max_samples: 3000
    Rminus1_stop: 0.05
    Rminus1_cl_stop: 0.08
    Rminus1_cl_level: 0.95
    Rminus1_single_split: 4
    measure_speeds: true
    oversample_power: 0.4
    oversample_thin: true
    drag: false
    blocking:
    - - 1
      - - H0
    - - 7
      - - alpha_jla
        - beta_jla
    callback_function: null
    callback_every: null
    seed: null
    check_every: 30
    oversample: null
    drag_limits: null
    fallback_covmat_scale: 4
    version: '3.6'
output: .
version: '3.6'
